name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: cd src && yarn --frozen-lockfile
    - name: Build
      run: cd src && yarn build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        files: "src/.serverless/cloudfront-sg-lambda.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
